# Generated by Django 2.1.15 on 2020-02-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chengji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuwen', models.CharField(max_length=10)),
                ('shuxue', models.CharField(max_length=10)),
                ('yingyu', models.CharField(max_length=10)),
                ('kexue', models.CharField(max_length=10)),
                ('yinyue', models.CharField(max_length=10)),
                ('meishu', models.CharField(max_length=10)),
                ('tiyu', models.CharField(max_length=10)),
                ('xinxi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nianji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoming', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('xingbie', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('jiguan', models.CharField(max_length=10)),
                ('zhuzhi', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Banji')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonghao', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('xingbie', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('nianji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Nianji')),
            ],
        ),
        migrations.AddField(
            model_name='chengji',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student'),
        ),
        migrations.AddField(
            model_name='chengji',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Teacher'),
        ),
        migrations.AddField(
            model_name='banji',
            name='nianji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Nianji'),
        ),
    ]
